"""alter profile add gender

Revision ID: 42b8cd7da4f9
Revises: 59a4c78f75d6
Create Date: 2021-02-20 12:42:23.789988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b8cd7da4f9'
down_revision = '59a4c78f75d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('gender', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'gender')
    # ### end Alembic commands ###
